# Generated by Django 4.2.1 on 2023-12-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0002_customuser_delete_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser", old_name="country", new_name="zip",
        ),
    ]
