# Generated by Django 4.2.1 on 2023-12-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0009_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="zipCode",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
