# Generated by Django 4.2.1 on 2023-12-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0011_alter_customuser_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="zipCode",
            field=models.IntegerField(null=True),
        ),
    ]
