# Generated by Django 4.2.1 on 2023-12-12 13:56

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0012_alter_customuser_zipcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="blog")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Mental Health", "Mental Health"),
                            ("Heart Disease", "Heart Disease"),
                            ("Covid 19", "Covid 19"),
                            ("Immunization", "Immunization"),
                        ],
                        max_length=50,
                    ),
                ),
                ("summary", models.CharField(max_length=15)),
                ("content", froala_editor.fields.FroalaField()),
                ("draft", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=1000)),
            ],
        ),
    ]
