# Generated by Django 4.2.1 on 2023-12-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0014_alter_blogmodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="summary",
            field=models.CharField(max_length=500),
        ),
    ]
