# Generated by Django 4.2.8 on 2023-12-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0016_blogmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="summary",
            field=models.CharField(max_length=1000),
        ),
    ]
